// <auto-generated />
using System;
using CianLib.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CianLib.Migrations
{
    [DbContext(typeof(CianContext))]
    partial class CianContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CianLoader.Model.Offer", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("added")
                        .HasColumnType("int");

                    b.Property<int?>("builders_ids")
                        .HasColumnType("int");

                    b.Property<string>("category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cian_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("creation_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("deal_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("filter_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("from_developer")
                        .HasColumnType("bit");

                    b.Property<int?>("house_id")
                        .HasColumnType("int");

                    b.Property<float>("lat")
                        .HasColumnType("real");

                    b.Property<float>("lon")
                        .HasColumnType("real");

                    b.Property<int?>("newobject_id")
                        .HasColumnType("int");

                    b.Property<int?>("object_type")
                        .HasColumnType("int");

                    b.Property<string>("photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("price")
                        .HasColumnType("bigint");

                    b.Property<int>("property_type")
                        .HasColumnType("int");

                    b.Property<int>("service_id")
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<int>("city")
                        .HasColumnType("int");

                    b.Property<int?>("village_id")
                        .HasColumnType("int");

                    b.Property<long>("row_id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("date");

                    b.HasKey("row_id");

                    b.ToTable("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
